// Copyright 2025 kerikun11
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

/* SPI */
#undef RP_SPI_USE_SPI0
#define RP_SPI_USE_SPI0 TRUE
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP22
#define SPI_MISO_PIN GP20
#define SPI_MOSI_PIN GP23

/* Pointing Device */
#define POINTING_DEVICE_CS_PIN GP21
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_ROTATION_90
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE

/* Split */
#define SPLIT_HAND_MATRIX_GRID_LOW_IS_LEFT
#define SPLIT_POINTING_ENABLE

// #define AUTO_MOUSE_DEFAULT_LAYER 1

// #define TAP_CODE_DELAY 5
