#!/usr/bin/env python3
"""Generate the firmware's as-flashed default keycode values, per layer and
per key, so the editor can highlight keys that a user has since changed
from the device's live (EEPROM) state.

There is no VIA command to read the compiled-in default without erasing the
live EEPROM copy (id_dynamic_keymap_reset overwrites it), so this script
reads the default/keymap.c that the firmware was actually built from, and
resolves every key expression down to the exact numeric keycode QMK would
compile it to, using build_keycodes.py's shared expression resolver.
"""

from __future__ import annotations

import json
import re
import subprocess
from datetime import datetime, timedelta, timezone
from pathlib import Path

import build_keycodes as keycodes

REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
KEYBOARD_ROOT = REPOSITORY_ROOT / "software/qmk/keyboards/kerigokbd"
OUTPUT_DIR = Path(__file__).resolve().parents[1] / "public/generated"


def layout_version(keymap_path: Path) -> str:
    """The committed keymap.c history's latest date (JST), with a lettered
    suffix for same-day revisions, as "how current is this default
    keymap"."""
    def git(*args: str) -> str:
        return subprocess.check_output(["git", "-C", str(REPOSITORY_ROOT), *args], text=True).strip()

    if git("rev-parse", "--is-shallow-repository") == "true":
        raise ValueError("Layout version requires full Git history (fetch-depth: 0).")
    history = git("log", "--follow", "--format=%cI", "--", str(keymap_path.relative_to(REPOSITORY_ROOT)))
    if not history:
        raise ValueError("No committed history found for keymap.c.")
    jst = timezone(timedelta(hours=9))
    dates = [datetime.fromisoformat(line).astimezone(jst).date() for line in history.splitlines()]
    latest = dates[0]
    revision = dates.count(latest)
    suffix = ""
    while revision:
        revision, remainder = divmod(revision - 1, 26)
        suffix = chr(ord("a") + remainder) + suffix
    return f"v{latest:%Y.%m.%d}{suffix}"


def parse_keymap_layers(source: str) -> dict[str, list[str]]:
    """Same shape as build_keycodes' generic C-macro-args parsing, applied
    to `[LAYER] = LAYOUT_xxx(...)` declarations in default/keymap.c."""
    clean_source = keycodes.strip_line_comments(re.sub(r"/\*.*?\*/", "", source, flags=re.S))
    declaration = re.compile(r"\[(KGL_[A-Z0-9_]+)\]\s*=\s*(LAYOUT_[A-Za-z0-9_]+)\s*\(")
    layers: dict[str, list[str]] = {}
    for match in declaration.finditer(clean_source):
        opening = match.end() - 1
        closing = keycodes.matching_parenthesis(clean_source, opening)
        layers[match.group(1)] = keycodes.split_arguments(clean_source[opening + 1:closing])
    return layers


def build_keyboard_defaults(keyboard_id: str, resolver: "keycodes.Resolver", layer_names: list[str]) -> dict[str, object]:
    keymap_path = KEYBOARD_ROOT / keyboard_id / "keymaps/default/keymap.c"
    parsed = parse_keymap_layers(keymap_path.read_text(encoding="utf-8"))
    layers = []
    for layer_name in layer_names:
        if layer_name not in parsed:
            break  # kerigokbd_v1's keymap.c doesn't define KGL_AM
        layers.append([resolver.resolve_keycode(expression) for expression in parsed[layer_name]])
    return {"id": keyboard_id, "layers": layers, "layoutVersion": layout_version(keymap_path)}


def build_resolver():
    registry = keycodes.load_keycode_registry()
    symbols = keycodes.build_symbol_table(registry)
    japanese = keycodes.resolve_japanese_aliases(symbols)
    kerigokbd_header_text = (KEYBOARD_ROOT / "kerigokbd.h").read_text(encoding="utf-8")

    layer_names = keycodes.parse_layers(kerigokbd_header_text)
    layer_index = {name: index for index, name in enumerate(layer_names)}

    custom_keycode_aliases = keycodes.parse_kerigokbd_custom_keycodes(kerigokbd_header_text)
    values_by_symbol = {**symbols, **japanese, **{
        alias: symbols[base] for alias, base in custom_keycode_aliases.items()
    }}
    macros = keycodes.parse_kerigokbd_macros(kerigokbd_header_text)
    resolver = keycodes.Resolver(values_by_symbol, macros, layer_index)
    return resolver, layer_names


def main() -> None:
    resolver, layer_names = build_resolver()
    for keyboard_id in ("kerigokbd_v1", "kerigokbd_v2"):
        defaults = build_keyboard_defaults(keyboard_id, resolver, layer_names)
        output_path = OUTPUT_DIR / f"defaults-{keyboard_id}.js"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        serialized = json.dumps(defaults, ensure_ascii=False, indent=2)
        output_path.write_text(
            "// Generated by scripts/build_defaults.py. Do not edit by hand.\n"
            f"export const DEFAULTS = {serialized};\n",
            encoding="utf-8",
        )
        print(f"Generated {output_path.relative_to(REPOSITORY_ROOT)} "
              f"({len(defaults['layers'])} layers)")


if __name__ == "__main__":
    main()
