// Copyright 2025 KERI's Lab
// SPDX-License-Identifier: GPL-2.0-or-later
// config.h for Keyball RP2040

#pragma once

/* I2C */
#define I2C_DRIVER I2CD1 // see https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf#page=13
#define I2C1_SDA_PIN GP14
#define I2C1_SCL_PIN GP15

/* Pointing Device */
// #define POINTING_DEVICE_ROTATION_180
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE

/* Cirque Trackpad */
// #define CIRQUE_PINNACLE_DIAMETER_MM 35
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_1X //< most sensitive
// #define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_2X
// #define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_3X
// #define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_4X //< least sensitive
